# Generated by Django 2.1.3 on 2018-11-08 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=15)),
                ('sobrenome', models.CharField(max_length=15)),
                ('dt_nascimento', models.DateTimeField()),
                ('nacionalidade', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='clienteCobranca',
            fields=[
                ('numeroCartao', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('cvv', models.CharField(max_length=3)),
                ('validade', models.CharField(max_length=5)),
                ('bandeiraCartao', models.CharField(max_length=25)),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.cliente')),
            ],
            options={
                'verbose_name_plural': 'Cartões',
            },
        ),
        migrations.CreateModel(
            name='clientePlano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.cliente')),
            ],
            options={
                'verbose_name_plural': 'Planos dos clientes',
            },
        ),
        migrations.CreateModel(
            name='endereco',
            fields=[
                ('cep', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('rua', models.CharField(max_length=50)),
                ('bairro', models.CharField(default='null', max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('complemento', models.CharField(max_length=50)),
                ('numero', models.PositiveIntegerField()),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.cliente', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Endereços Clientes',
            },
        ),
        migrations.CreateModel(
            name='enderecoCobranca',
            fields=[
                ('cep', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('rua', models.CharField(default='', max_length=50)),
                ('bairro', models.CharField(default='', max_length=50)),
                ('cidade', models.CharField(default='', max_length=50)),
                ('estado', models.CharField(default='', max_length=50)),
                ('pais', models.CharField(default='', max_length=50)),
                ('complemento', models.CharField(default='', max_length=50)),
                ('numero', models.PositiveIntegerField()),
                ('numeroCartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.clienteCobranca')),
            ],
            options={
                'verbose_name_plural': 'Endereços Cobrança Clientes',
            },
        ),
        migrations.CreateModel(
            name='guardaVolume',
            fields=[
                ('num', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('ocupacao', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Guarda Volumes',
            },
        ),
        migrations.CreateModel(
            name='hub',
            fields=[
                ('idHub', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('quantGuardaVolumes', models.PositiveIntegerField()),
                ('coordw', models.CharField(max_length=12)),
                ('coords', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='log',
            fields=[
                ('datahora', models.DateTimeField(primary_key=True, serialize=False)),
                ('acao', models.CharField(max_length=20)),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='plano',
            fields=[
                ('idPlano', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30)),
                ('valor', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='telefone_cliente',
            fields=[
                ('telefone', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.cliente')),
            ],
            options={
                'verbose_name_plural': 'Telefones Clientes',
            },
        ),
        migrations.CreateModel(
            name='usa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHoraInicio', models.DateTimeField()),
                ('dataHoraFim', models.DateTimeField()),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.cliente')),
                ('idGuardaVolume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.guardaVolume')),
            ],
            options={
                'verbose_name_plural': 'Logs dos lockers',
            },
        ),
        migrations.AddField(
            model_name='guardavolume',
            name='idHub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.hub'),
        ),
        migrations.AddField(
            model_name='clienteplano',
            name='idPlano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.plano'),
        ),
    ]
